// 聊天界面检查：发送、轮询收消息、私聊、附件、@ 候选、禁言开关与提示
import {spawn} from 'node:child_process';
import WebSocket from '../../node_modules/ws/index.js';
const SITE=process.env.BASE_URL||'http://127.0.0.1:4173';
const PORT=Number(process.env.CDP_PORT||9433),profile='/tmp/cdp-chat-'+Date.now();
const chrome=spawn('google-chrome',['--headless=new','--disable-gpu','--no-sandbox','--disable-dev-shm-usage','--window-size=1440,1100','--remote-debugging-port='+PORT,'--user-data-dir='+profile,'about:blank'],{stdio:'ignore',detached:true});chrome.unref();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
for(let i=0;i<60;i++){try{const r=await fetch('http://127.0.0.1:'+PORT+'/json/version');if(r.ok)break}catch(error){}await sleep(500)}
const target=await (await fetch('http://127.0.0.1:'+PORT+'/json/new?'+encodeURIComponent(SITE+'/'),{method:'PUT'})).json();
const ws=new WebSocket(target.webSocketDebuggerUrl,{maxPayload:64*1024*1024});
await new Promise((resolve,reject)=>{ws.on('open',resolve);ws.on('error',reject)});
let id=0;const pending=new Map();const errors=[];
ws.on('message',raw=>{const m=JSON.parse(raw.toString());
 if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);return}
 if(m.method==='Runtime.exceptionThrown')errors.push('EXCEPTION '+String(m.params.exceptionDetails.exception?.description||'').slice(0,150));
 if(m.method==='Page.javascriptDialogOpening')ws.send(JSON.stringify({id:++id,method:'Page.handleJavaScriptDialog',params:{accept:true}}))});
const send=(method,params={})=>{const i=++id;ws.send(JSON.stringify({id:i,method,params}));return new Promise((resolve,reject)=>pending.set(i,{resolve,reject}))};
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw new Error('eval: '+String(r.exceptionDetails.exception?.description||'').slice(0,200));return r.result.value};
const waitFor=async(expression,timeout=30000)=>{const t0=Date.now();while(Date.now()-t0<timeout){try{if(await evaluate(expression))return true}catch(error){}await sleep(400)}return false};
const results=[];const check=(name,ok,extra)=>{console.log((ok?'PASS':'FAIL')+' :: '+name+(extra?' :: '+String(extra).slice(0,200):''));results.push(ok)};const HELPERS='window.__adminCreds='+JSON.stringify([[process.env.ADMIN_USER||'admin',process.env.ADMIN_PASSWORD||'Local-New-Password-827!'],['admin','Local-New-Password-827!'],['admin','Local-Test-Password-827!'],['admin','E2E-Admin-Password-827!'],['owner','E2E-Admin-Password-827!']])+';window.__adminLogin=async()=>{const me=await (await fetch("/api/me")).json();if(me.user&&me.user.role==="admin")return 200;for(const [username,password] of window.__adminCreds){const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});if(r.status!==200)continue;const state=await (await fetch("/api/me")).json();if(state.user&&state.user.mustChange){const changed=await fetch("/api/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({oldPassword:password,password:"Local-New-Password-827!"})});return changed.status}return 200}return 0};';
const MATE='window.__mateLogin=async()=>{const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"chatmate",password:"ChatMate-Password-828!"})});if(r.status===200)return 200;const alt=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"chatmate",password:"ChatMate-Password-827!"})});if(alt.status!==200)return alt.status;const me=await (await fetch("/api/me")).json();if(me.user&&me.user.mustChange){await fetch("/api/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({oldPassword:"ChatMate-Password-827!",password:"ChatMate-Password-828!"})})}return 200};';const stamp=Date.now().toString(36).slice(-6);
await send('Runtime.enable');await send('Page.enable');
await send('Page.navigate',{url:SITE+'/'});await sleep(2500);
await sleep(300);await evaluate(HELPERS+MATE+'true');
await evaluate(HELPERS+MATE+'true');
const login=await evaluate('window.__adminLogin()');
check('管理员登录',login===200,'status='+login);
const prepared=await evaluate('(async()=>{const me=await (await fetch("/api/me")).json();if(!me.user)return "no-session";const list=await (await fetch("/api/users")).json();let mate=list.users.find(u=>u.username==="chatmate");if(!mate){await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"chatmate",name:"聊天同学",password:"ChatMate-Password-827!"})});const again=await (await fetch("/api/users")).json();mate=again.users.find(u=>u.username==="chatmate")}return JSON.stringify({mate:mate&&mate.id})})()');
console.log('prepared:',prepared);
await evaluate('window.__mateLogin()');await sleep(500);
await evaluate('(async()=>{const me=await (await fetch("/api/me")).json();if(me.user&&me.user.mustChange)return "mate-must-change";await fetch("/api/logout",{method:"POST"});return "ok"})()');
await evaluate('window.__adminLogin()');await sleep(400);
await send('Page.navigate',{url:SITE+'/chat/'});await sleep(3500);
await sleep(300);await evaluate(HELPERS+MATE+'true');
check('聊天页面有会话列表与输入框',await evaluate('!!document.querySelector("#chatRooms")&&!!document.querySelector("#chatInput")&&!!document.querySelector("#chatThread")'));
check('默认进入班级大群',/班级大群/.test(await evaluate('document.querySelector("#chatTitle")?document.querySelector("#chatTitle").textContent:""')));
const sent=await evaluate('(async()=>{const input=document.querySelector("#chatInput");input.value="界面测试：大家好";document.querySelector("#chatForm").requestSubmit();await new Promise(r=>setTimeout(r,1800));const bubbles=[...document.querySelectorAll(".chat-msg")];const last=bubbles[bubbles.length-1];return JSON.stringify({mine:last?last.classList.contains("mine"):false,text:last?last.textContent.replace(/\\s+/g," " ).slice(0,60):""})})()');
check('在界面上发送消息并显示在自己的气泡里',JSON.parse(sent).mine===true&&/界面测试/.test(JSON.parse(sent).text),sent);
const reply=await evaluate('(async()=>{const r=await window.__mateLogin();if(r!==200)return "login="+r;const sent=await fetch("/api/chat/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({room:"class",body:"同学回复：收到啦"})});await fetch("/api/logout",{method:"POST"});await window.__adminLogin();return String(sent.status)})()');
check('另一位同学在大群发言',reply==='201',reply);
check('不刷新页面也能收到对方消息（轮询）',await waitFor('[...document.querySelectorAll(".chat-msg")].some(node=>node.textContent.indexOf("同学回复：收到啦")>=0)',15000),'waiting');const direct=await evaluate('(async()=>{const rows=[...document.querySelectorAll(".chat-room")];const mate=rows.find(row=>/聊天同学/.test(row.textContent));if(!mate)return "no-room";mate.click();await new Promise(r=>setTimeout(r,1500));document.querySelector("#chatInput").value="私聊测试：明天值日";document.querySelector("#chatForm").requestSubmit();await new Promise(r=>setTimeout(r,1500));return JSON.stringify({title:document.querySelector("#chatTitle").textContent,last:[...document.querySelectorAll(".chat-msg")].pop().textContent.replace(/\\s+/g," " ).slice(0,50)})})()');
check('可以进入和同学的私聊并发消息',/聊天同学/.test(direct)&&/私聊测试/.test(direct),direct);
const removed=await evaluate('(async()=>{const bubbles=[...document.querySelectorAll(".chat-msg")];const last=bubbles[bubbles.length-1];const button=last.querySelector("[data-del]");if(!button)return "no-button";const before=bubbles.length;button.click();await new Promise(r=>setTimeout(r,1800));return JSON.stringify({before,after:document.querySelectorAll(".chat-msg").length})})()');
check('可以撤回自己发送的消息',JSON.parse(removed).after===JSON.parse(removed).before-1,removed);
await evaluate('document.querySelector(".chat-room").click();true');await sleep(1500);
check('聊天页有附件按钮',await evaluate('!!document.querySelector("#chatPick")'));
const mentionUi=await evaluate('(async()=>{const input=document.querySelector("#chatInput");input.value="@";input.dispatchEvent(new Event("input",{bubbles:true}));await new Promise(r=>setTimeout(r,500));const box=document.querySelector("#chatMentions");return JSON.stringify({hidden:box.hidden,options:box.querySelectorAll("button").length})})()');
check('输入 @ 会出现同学候选',JSON.parse(mentionUi).hidden===false&&JSON.parse(mentionUi).options>=1,mentionUi);
const attached=await evaluate('(async()=>{const canvas=document.createElement("canvas");canvas.width=80;canvas.height=60;const ctx=canvas.getContext("2d");ctx.fillStyle="#2f6df6";ctx.fillRect(0,0,80,60);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png"));const file=new File([blob],"界面配图.png",{type:"image/png"});const picker=document.querySelector("#chatFile");const dt=new DataTransfer();dt.items.add(file);picker.files=dt.files;picker.dispatchEvent(new Event("change",{bubbles:true}));await new Promise(r=>setTimeout(r,700));const chip=document.querySelector("#chatFileChip");const showed=!chip.hidden;document.querySelector("#chatInput").value="看这张图";document.querySelector("#chatForm").requestSubmit();await new Promise(r=>setTimeout(r,3000));return JSON.stringify({showed,images:document.querySelectorAll(".chat-image img").length})})()');
check('可以发送图片并显示在气泡里',JSON.parse(attached).showed===true&&JSON.parse(attached).images>=1,attached);
await send('Page.navigate',{url:SITE+'/admin/?tab=data'});await sleep(3500);
await sleep(300);await evaluate(HELPERS+MATE+'true');
const muteUi=await evaluate('JSON.stringify({group:!!document.querySelector("[data-action=muteGroup]"),direct:!!document.querySelector("[data-action=muteDirect]"),settings:!!document.querySelector("#chatSettings"),recall:!!document.querySelector("#chatRecall"),cleanup:!!document.querySelector("#chatCleanup")})');
const muteInfo=JSON.parse(muteUi);
check('后台有群聊/私聊禁言开关',muteInfo.group&&muteInfo.direct,muteUi);
check('后台有聊天设置（撤回时限/自动清理/立即清理）',muteInfo.settings&&muteInfo.recall&&muteInfo.cleanup,muteUi);
const toggled=await evaluate('(async()=>{const button=document.querySelector("[data-action=muteGroup]");const before=button.getAttribute("aria-pressed");button.click();await new Promise(r=>setTimeout(r,2000));const fresh=document.querySelector("[data-action=muteGroup]");return JSON.stringify({before,after:fresh?fresh.getAttribute("aria-pressed"):null,label:fresh?fresh.textContent.trim():""})})()');
check('点击开关可以禁言/解禁大群',JSON.parse(toggled).before!==JSON.parse(toggled).after,toggled);
const saved=await evaluate('(async()=>{document.querySelector("#chatRecall").value="15";document.querySelector("#chatSettings button[type=submit]").click();await new Promise(r=>setTimeout(r,1600));const data=await (await fetch("/api/settings")).json();return String(data.settings.chatRecall)})()');
check('聊天设置可以保存',saved==='15','chatRecall='+saved);
await evaluate('(async()=>{document.querySelector("#chatRecall").value="10";document.querySelector("#chatSettings button[type=submit]").click();await new Promise(r=>setTimeout(r,1400));return true})()');
await evaluate('(async()=>{const users=await (await fetch("/api/users")).json();const mate=users.users.find(u=>u.username==="chatmate");await fetch("/api/users/"+mate.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({muteGroup:true})});await window.__mateLogin();return true})()');
await send('Page.navigate',{url:SITE+'/chat/'});await sleep(3000);
await sleep(300);await evaluate(HELPERS+MATE+'true');
const mutedView=await evaluate('JSON.stringify({disabled:document.querySelector("#chatInput").disabled,banner:!document.querySelector("#chatMuted").hidden,text:document.querySelector("#chatMuted").textContent})');
check('被禁言时输入框禁用并给出提示',JSON.parse(mutedView).disabled===true&&JSON.parse(mutedView).banner===true,mutedView);
await evaluate('(async()=>{await window.__adminLogin();const users=await (await fetch("/api/users")).json();const mate=users.users.find(u=>u.username==="chatmate");await fetch("/api/users/"+mate.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({muteGroup:false})});return true})()');
check('控制台无错误',errors.length===0,errors.slice(0,2).join(' | '));
console.log('TOTAL',results.length,', FAILED',results.filter(ok=>!ok).length);
ws.close();chrome.kill('SIGKILL');process.exit(results.filter(ok=>!ok).length?1:0);