// 网络传输与自适应验证：缩略图 / 封面 / 按需原图 / 只读接口 ETag / 悬停预取 / 网络档位
import {spawn} from 'node:child_process';
import WebSocket from '../../node_modules/ws/index.js';
const SITE=process.env.BASE_URL||'http://127.0.0.1:4173';
const PORT=Number(process.env.CDP_PORT||9413),profile='/tmp/cdp-net-'+Date.now();
const chrome=spawn('google-chrome',['--headless=new','--disable-gpu','--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required','--window-size=1440,1100','--remote-debugging-port='+PORT,'--user-data-dir='+profile,'about:blank'],{stdio:'ignore',detached:true});chrome.unref();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
for(let i=0;i<60;i++){try{const r=await fetch('http://127.0.0.1:'+PORT+'/json/version');if(r.ok)break}catch(error){}await sleep(500)}
const target=await (await fetch('http://127.0.0.1:'+PORT+'/json/new?'+encodeURIComponent(SITE+'/'),{method:'PUT'})).json();
const ws=new WebSocket(target.webSocketDebuggerUrl,{maxPayload:64*1024*1024});
await new Promise((resolve,reject)=>{ws.on('open',resolve);ws.on('error',reject)});
let id=0;const pending=new Map();const errors=[];const reqs=[];
ws.on('message',raw=>{const m=JSON.parse(raw.toString());
 if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result);return}
 if(m.method==='Runtime.exceptionThrown')errors.push('EXCEPTION '+String(m.params.exceptionDetails.exception?.description||'').slice(0,150));
 if(m.method==='Network.requestWillBeSent')reqs.push(m.params.request.url)});
const send=(method,params={})=>{const i=++id;ws.send(JSON.stringify({id:i,method,params}));return new Promise((resolve,reject)=>pending.set(i,{resolve,reject}))};
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw new Error('eval: '+String(r.exceptionDetails.exception?.description||'').slice(0,200));return r.result.value};
const waitFor=async(expression,timeout=30000)=>{const t0=Date.now();while(Date.now()-t0<timeout){try{if(await evaluate(expression))return true}catch(error){}await sleep(300)}return false};
const results=[];const check=(name,ok,extra)=>{console.log((ok?'PASS':'FAIL')+' :: '+name+(extra?' :: '+String(extra).slice(0,220):''));results.push(ok)};
await send('Runtime.enable');await send('Page.enable');await send('Network.enable');
await send('Page.navigate',{url:SITE+'/'});await sleep(2500);
const CREDS=JSON.stringify([[process.env.ADMIN_USER||'admin',process.env.ADMIN_PASSWORD||'Local-New-Password-827!'],['admin','Local-New-Password-827!'],['admin','Local-Test-Password-827!'],['admin','E2E-Admin-Password-827!'],['owner','E2E-Admin-Password-827!']]);
const login=await evaluate('(async()=>{const attempt=async (user,password)=>{const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:user,password})});return r.status};for(const [user,password] of '+CREDS+'){if(await attempt(user,password)===200)return 200}return 0})()');
check('管理员登录',login===200,'status='+login);
const forced=await evaluate('(async()=>{const me=await (await fetch("/api/me")).json();if(!me.user||!me.user.mustChange)return "skip";const r=await fetch("/api/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({oldPassword:"Local-Test-Password-827!",password:"Local-New-Password-827!"})});return String(r.status)})()');
if(forced!=='skip')console.log('forced change:',forced);
const changed=await evaluate('(async()=>{const me=await (await fetch("/api/me")).json();if(!me.user||!me.user.mustChange)return "skip";const r=await fetch("/api/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({oldPassword:"Local-Test-Password-827!",password:"Local-New-Password-827!"})});return String(r.status)})()');
console.log('forced change:',changed);
// 网络档位
await send('Page.navigate',{url:SITE+'/'});await sleep(2500);
const profileState=await evaluate('JSON.stringify({profile:document.documentElement.dataset.net||"",source:document.documentElement.dataset.netSource||"",status:document.querySelector("#netStatus")?document.querySelector("#netStatus").textContent:"",choices:document.querySelectorAll("#netSeg [data-net-choice]").length})');
const profileInfo=JSON.parse(profileState);
check('自动判定网络档位并说明依据',['lite','balanced','quality'].indexOf(profileInfo.profile)>=0&&profileInfo.choices===4&&/判定/.test(profileInfo.status),profileState);
const siteCreated=await evaluate('(async()=>{const r=await fetch("/api/sites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"网络演示",slug:"net-demo",kind:"gallery",description:"自适应演示"})});return r.status})()');
check('准备图册站点',siteCreated===201||siteCreated===409,'status='+siteCreated);
await send('Page.navigate',{url:SITE+'/admin/?tab=data&focus=upload'});await sleep(3500);
await evaluate('(()=>{const select=document.querySelector("#site");const option=[...select.options].find(o=>o.textContent.indexOf("网络演示")>=0);if(option)select.value=option.value;return true})()');
const injected=await evaluate('(async()=>{const makeImage=(size)=>{const canvas=document.createElement("canvas");canvas.width=size;canvas.height=Math.round(size*0.75);const ctx=canvas.getContext("2d");const data=ctx.createImageData(canvas.width,canvas.height);for(let i=0;i<data.data.length;i+=4){data.data[i]=Math.floor(Math.random()*256);data.data[i+1]=Math.floor(Math.random()*256);data.data[i+2]=Math.floor(Math.random()*256);data.data[i+3]=255}ctx.putImageData(data,0,0);return new Promise(resolve=>canvas.toBlob(blob=>resolve(new File([blob],"大图.png",{type:"image/png"})),"image/png"))};const makeVideo=async()=>{const canvas=document.createElement("canvas");canvas.width=320;canvas.height=240;const ctx=canvas.getContext("2d");const stream=canvas.captureStream(12);const chunks=[];let recorder=null;try{recorder=new MediaRecorder(stream,{mimeType:"video/webm"})}catch(error){return null}recorder.ondataavailable=event=>{if(event.data&&event.data.size)chunks.push(event.data)};recorder.start();let tick=0;const timer=setInterval(()=>{tick++;ctx.fillStyle="hsl("+(tick*24%360)+",70%,45%)";ctx.fillRect(0,0,320,240);ctx.fillStyle="#fff";ctx.font="28px sans-serif";ctx.fillText("第"+tick+"帧",20,130)},90);await new Promise(r=>setTimeout(r,1500));clearInterval(timer);await new Promise(resolve=>{recorder.onstop=resolve;recorder.stop()});const blob=new Blob(chunks,{type:"video/webm"});return blob.size?new File([blob],"动画.webm",{type:"video/webm"}):null};const image=await makeImage(2000);const video=await makeVideo();const files=[image];if(video)files.push(video);const dt=new DataTransfer();files.forEach(file=>dt.items.add(file));const input=document.querySelector("#file");input.files=dt.files;input.dispatchEvent(new Event("change",{bubbles:true}));return JSON.stringify({count:files.length,imageSize:image.size,videoSize:video?video.size:0})})()');
check('后台上传图片与视频',JSON.parse(injected).count>=1,injected);
const prepared=await waitFor('/已准备 [0-9]+ 个文件/.test(document.querySelector("#progress").textContent)&&!document.querySelector("#upload button[type=submit]").disabled',90000);
check('客户端生成缩略图/封面后可以提交',prepared,await evaluate('document.querySelector("#progress").textContent'));
await evaluate('document.querySelector("#upload").dispatchEvent(new Event("submit",{cancelable:true,bubbles:true}));true');
check('上传完成并跳转媒体库',await waitFor('location.pathname.indexOf("/sites/net-demo")===0',120000),await evaluate('location.href'));
const docs=await evaluate('(async()=>{const r=await (await fetch("/api/documents?site=net-demo")).json();return JSON.stringify(r.documents.map(d=>({id:d.id,type:d.file_type,size:d.size,thumb:!!(d.meta&&d.meta.thumb)})))})()');
const docList=JSON.parse(docs);const photo=docList.find(d=>['webp','png','jpg'].indexOf(d.type)>=0);
check('图片带服务端缩略图记录',!!photo&&photo.thumb===true,docs);
const thumbInfo=await evaluate('(async()=>{const r=await fetch("/api/documents/'+photo.id+'/thumb");const blob=await r.blob();return JSON.stringify({status:r.status,type:r.headers.get("content-type"),cache:r.headers.get("cache-control"),size:blob.size})})()');
const thumb=JSON.parse(thumbInfo);
check('缩略图是 WEBP 且可长期缓存',thumb.status===200&&/image\/webp/.test(thumb.type||'')&&/immutable/.test(thumb.cache||''),thumbInfo);
check('缩略图远小于原图',thumb.size<photo.size/2,thumb.size+' vs '+photo.size);
await send('Page.navigate',{url:SITE+'/sites/net-demo/'});await sleep(2500);
const grid=await evaluate('JSON.stringify({tiles:[...document.querySelectorAll(".tile")].map(t=>({img:t.querySelector("img")?t.querySelector("img").getAttribute("src"):null,video:t.querySelector("video")?t.querySelector("video").getAttribute("preload"):null}))})');
const tiles=JSON.parse(grid).tiles;
check('网格用缩略图而不是原图',tiles.filter(t=>t.img).length>=1&&tiles.filter(t=>t.img).every(t=>t.img.indexOf('/thumb')>=0),grid);
check('网格不预先下载视频数据',tiles.every(t=>!t.video||t.video==='none'),grid);
const apiCache=await evaluate('(async()=>{const first=await fetch("/api/sites",{credentials:"same-origin"});await first.json();const second=await fetch("/api/sites",{credentials:"same-origin"});await second.json();return JSON.stringify({cache:first.headers.get("cache-control"),etag:!!first.headers.get("etag"),second:second.status})})()');
const cache=JSON.parse(apiCache);
check('只读接口带 ETag 与私有缓存',cache.etag===true&&/private/.test(cache.cache||''),apiCache);
await evaluate('document.querySelector("#prefsToggle").click();true');await sleep(300);
await evaluate('document.querySelector("[data-net-choice=lite]").click();true');await sleep(400);
await evaluate('document.querySelector("#prefsToggle").click();true');await sleep(200);
await send('Page.navigate',{url:SITE+'/sites/net-demo/?doc='+photo.id});await sleep(3000);
const adaptive=await evaluate('JSON.stringify({src:document.querySelector("#mediaEl")?document.querySelector("#mediaEl").getAttribute("src"):null,full:document.querySelector("#mediaEl")?document.querySelector("#mediaEl").dataset.full:null,button:!!document.querySelector("[data-load-full]")})');
const adaptiveInfo=JSON.parse(adaptive);
check('省流模式先显示缩略图并给出“加载原图”',/\/thumb$/.test(adaptiveInfo.src||'')&&adaptiveInfo.button===true,adaptive);
const loaded=await evaluate('(async()=>{const button=document.querySelector("[data-load-full]");if(button)button.click();await new Promise(r=>setTimeout(r,4000));return document.querySelector("#mediaEl").getAttribute("src")})()');
check('点“加载原图”后切换到原图',String(loaded).indexOf(adaptiveInfo.full||'__')>=0,loaded);
reqs.length=0;
await evaluate('(()=>{const link=[...document.querySelectorAll("#nav a")].find(a=>a.getAttribute("href")==="/timetable/");if(link)link.dispatchEvent(new PointerEvent("pointerover",{bubbles:true}));return true})()');await sleep(800);
check('省流模式不预取',reqs.filter(u=>u.indexOf('/api/timetable')>=0).length===0,reqs.filter(u=>u.indexOf('/api/')>=0).join(' '));
await evaluate('document.querySelector("#prefsToggle").click();true');await sleep(250);
await evaluate('document.querySelector("[data-net-choice=quality]").click();true');await sleep(400);
reqs.length=0;
await evaluate('(()=>{const link=[...document.querySelectorAll("#nav a")].find(a=>a.getAttribute("href")==="/timetable/");if(link)link.dispatchEvent(new PointerEvent("pointerover",{bubbles:true}));return true})()');await sleep(1200);
check('高清模式会预取下一页数据',reqs.filter(u=>u.indexOf('/api/timetable')>=0).length===1,reqs.filter(u=>u.indexOf('/api/')>=0).join(' '));
await evaluate('document.querySelector("#prefsToggle").click();true');await sleep(200);
await evaluate('document.querySelector("[data-net-choice=auto]").click();true');await sleep(300);
check('控制台无错误',errors.length===0,errors.slice(0,2).join(' | '));
console.log('TOTAL',results.length,', FAILED',results.filter(ok=>!ok).length);
ws.close();chrome.kill('SIGKILL');process.exit(results.filter(ok=>!ok).length?1:0);